spring:
  application:
    name: withPat
  jackson:
    serialization:
      write-dates-as-timestamps: true
  main:
    allow-bean-definition-overriding: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  1000MB
      # 设置总上传的文件大小
      max-request-size:  2000MB
  datasource:
    url: jdbc:mysql://localhost:3306/pailide?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9501
#日志
logging:
  level:
    com.withpat: debug
    org.springframework: warn
#操作数据库的设置
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 项目相关配置
ruoyi:
  # 名称
  name: withPat
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/project/WithPat/with-pat/uploadPath/upload
# rsa配置
rsa:
  key:
    publicKey-file:  D:/project/WithPat/with-pat/auth_key/id_key_rsa.pub
    privateKey-file: D:/project/WithPat/with-pat/auth_key/id_key_rsa
    secret: (EMOK)_$^11244^%$_(IS)_@@++--(COOL:)_++++_:sds_(GUY)

token:
  #token头部
  header: Authorization
  #存储的key
  secret: with_pat_user
  #过期时间
  expiration: 10000000
